# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46843d1a80486a4b75169ada836717896c70016f7bf8594f723a04fd6058222183a475e901bd38a4f57b7705ad21903a36e1fa99a6b1359b187e5e1a380e483e

test:
  secret_key_base: b724579d11c23581e24839b00acf4483b0c397e86eefe03ffad313e7843f5522025e58d4ae8759c31efc63c0c18f233c35a9adc6b68589484daa23f684e4416d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
